var colors = ['#1abc9c','#2ecc71','#3498db','#9b59b6','#f1c40f','#e67e22','#e74c3c','#f39c12','#c0392b','#34495e'];
var messages = ["Every day I wake up excited to see a message from you (or wake up even more excited when you're next to me).",
"You're so understand when so many people in the world are dismissive.",
"You're so incredibly kind-hearted and caring towards others.",
"Seeing your smile instantly makes me happy even when I'm feeling down.",
"You inspire me to be more creative every day.",
"You motivate me to be a better person.",
"You've helped me rekindle my enjoyment of reading (get it?)",
"You've helped me so much to be more confident in myself.",
"Every day with you is an incredible adventure that I never want to end.",
"You make everything so much fun, whether we're sitting around watching TV or roaming the streets of Seoul!",
"You're such an incredibly talented speaker, your stories always leave me wanting more!",
"You are a truly great writer. I'm always amazed at how fluidly you are able to come up with ideas and string together sentences. I hope one day you give yourself as much credit as you deserve!",
"I talk about you to people all the time. You're truly the cool one and I'm so happy I get to associate with you! :P",
"You're so open to trying new things with enthusiasm and an open mind.",
"You never talk poorly of others when most people might.",
"You have an infectious passion for life that makes me want to constantly experience new things.",
"You find excitement and enjoyment in the little things, not just the big things.",
"You make me laugh so hard sometimes my stomach hurts.",
"Sometimes when I look at you all words fail me and all I want to do is lean in and kiss you.",
"You're beautiful!",
"That look you give me when I do something truly stupid.",
"You grab my arm and pull me back when I try to get off at the wrong train station.",
"You grab my hand as we walk through city streets.",
"You make sure I'm not eating garbage in the garage.",
"You teach me so much and get me interested in things I'd never considered. (Impressionism is really cool!)",
"You translate for me when all I know how to say is seal...",
"You're willing to put up with my silly obsessions.",
"We can have deep discussions, disagree on all sorts of little things but still come to the same major conclussions. (or an appreciation for the other's POV!)",
"You introduce me to amazing new foods. SO MANY CREPES!!",
"You find enjoyment in seeing the enjoyment of others.",
"You laugh at my bad jokes and even worse puns",
"You're quick to put others before yourself.",
"You're so eager and willing to share.",
"You're so goddamn SEXY.",
"You take the time to really listen.",
"You love Neo & Gatsby just as much as I do. And they love you too!! (Just as much as I do.)",
"You find so many cool books to read and podcasts to listen to!!",
"We make so many delicious recipes together. (Though you do most of the work.)",
"You make such a comfy blanket or pillow while watching movies.",
"You find so many fun and unique things to do that I'd never think of on my own.",
"No, seriously. You're so beautiful.",
"Every time my phone vibrates I get excited that it might be from you.",
"You whoop my ass at trivia and make me want to learn more to beat you!",
"I squeeze you while we're laying down and you squeeze me back even tighter.",
"I look over while we're painting and see a big K+J on the wall!",
"The first time we met we talked so long we got kicked out of two places.",
"You hold my hand while reading and every once in a whole suprise me with a kiss.",
"You kept on me about sending a letter to my mom. (Turns out she did appreciate it.)",
"You like to learn about the weird tech stuff I enjoy that no one else cares about.",
"You inspire me to record more original songs. (Especially if the subject is you!)",
"You somehow always know just what to say and when to say it.",
"You come up behind me in bed and wrap your arm around me when I'm feeling crumby.",
"You rock sick Aviators with me in the car while we're cruisin'. And you pull them off better than I do!",
"You give me increasingly obvious signals when I'm being airheaded.",
"You let me do a k-pop dance in your room and didn't immediately kick me out!",
"You read to me in your amazing reading voice.",
"You're way into dinosaurs & hedgehogs.",
"You have so much knowledge about so many places in the world that I just want you to take me to all of them and share it with me!",
"Your singing voice is beautiful and you have no reason to be shy.",
"You have such an amazing sense of what's write and what's wrong.",
"You can be so silly and carefree and I can be the same around you.",
"Before I kissed you I never knew that a kiss really could feel like fireworks.",
"You are 100% genuine.",
"You have an incredible drive to get what you want in life.",
"You accept me, flaws and all. even though there are so many of them!!",
"You're an amazing teacher, wether it's english class or phy. ed.",
"You aren't afraid to take risks.",
"'What?'",
"You make me try things I never thought I'd try. (Like getting kneed for an hour by a giant man.)",
"You were willing to drive an hour to see me at night when I felt shitty with no hesitation.",
"You're so easy to be comfortable around.",
"When I drive down to your house I still get butterflies like it's the first time.",
"You cut a path for me to walk behind you in busy crowds.",
"You pull me the right way when I start walking off in the wrong direction coming off the subway.",
"Your excitement in the mornings fills me with energy to take on the day.",
"Your nutella chocolate pumpkin bread!",
"You grab me innapropriately at the funniest possible moments. INNAPROPRIATE.",
"The way your gentle hand feels running through my hair.",
"You're easy going and have no problems with sudden change in plans.",
"The way our bodies seem to fit together like puzzle pieces when laying down.",
"Your smile.",
"Your laugh.",
"The incredible look of dissapointment you give me.",
"Your little tremors as you fall asleep, especially when I can pull you closer to me and rub your arm till you fall deeper asleep.",
"I never knew I could enjoy sharing a pint of ice cream on the couch so much.",
"We both enjoy over the top silly movies. Usually involving Vin Diesel. Ok, always involving Vin Diesel.",
"You put up with my terrible, terrible french pronunciation even though it must be physically painful inside.",
"Your dance moves in the kitchen when we're cooking up a storm.",
"Going into new experiences without knowing what to expect, just knowing I'm glad that I'm sharing them with you.",
"We already act like an old married couple.",
"Even after a short time I felt like I had known you for years.",
"The way your eyes get big when you get really excited.",
"The way you violently shake me when you get really excited.",
"You aren't afraid to be yourself.",
"Your amusement at my very real and rational fear of giant objects in murky water. It's terrifying!",
"Your willingness to spend time and energy on my hobbies and interests.",
"You suprise me when I least expect it!",
"You keep me from messing with my fingernails. (I'm working on it!!!)",
"Your family is awesome!",
"You give me compliments when I need them the most.",
"You were the first person to ever say I was handsome.",
"You like Calvin and Hobbes just as much as me!",
"You're rabid obsession of Neko Atsume is adorable!",
"You can fall alseep in nearly any situation. It's truly a super power.",
"You introduce me to really cool new music!",
"We solve virtual crimes together.",
"Planning trips with you makes me feel like a kid on Christmas morning!",
"You make me take silly quizzes and then we analyze the results way too seriously.",
"We keep roleplaying during Clue long after everyone else playing has stopped. 'I seeeeeeee.'",
"You come up with so many fun and memorable date ideas!",
"You are willing to indulge my nerdy Star Trek fantasies :)",
"We meticulously lay out the table every time we eat dinner together.",
"You constantly amaze me.",
"You leave me speechless even when there's so much I want to say.",
"You enjoy being sappy just as much as I do.",
"You've taught me so much about the crazy airline industry and how it makes the grocery industry look sane!",
"You're incredibly financially responsible!",
"You are willing to make compromises.",
"You're an endless well of new ideas.",
"You're extraordinarily wise and give great advice.",
"You help me get over my irrational fears. Car washes aren't so scary!",
"You have well reasoned and carefully thought out ideas.",
"You don't worry about the future.",
"You have an amazing fashion sense.",
"You're even more beautiful on the inside than you are on the outside.",
"You make a real and positive difference in other peoples' lives.",
"You bring out the best in those around you.",
"You look incredible whether you're in fancy dinner clothes or around the house in pajamas.",
"You appreciate Ferd!",
"You're a great example of what a person should strive to be like.",
"Your airplane announcer voice is one of the cutest things I've ever heard.",
"We act so goofy in public together, even (especially) in places where everyone else is being serious.",
"You forcibly stop me from paying for things.",
"Sometimes when I see you I still feel the same way I did the first time you came through the door at 3 cellars.",
"Going through museums with you is like having my own personal expert!",
"You give me gifts for no reason.",
"When I'm with you I just wish I could take my finger and stop the clock hand from moving forward.",
"No matter how long we spend with eachother I miss you the moment you leave.",
"I've never thought more often throughout the day about a person than I think about you.",
"After a long, fun filled day we can lay down, put our arms around eachother and let out a long sigh.",
"I want you to be around all the time.",
"You can dish it out just as well as you can take it.",
"You make the greatest puns at the most random times.",
"This picture of you.",
"Looking out over cities and being more entranced by your reflection in the window.",
"I wanted to spend time with you so much that I secretly didn't finish all 180 of these with the secret plan to add the rest a different day!"];

function changeBackgroundColor(){
  var color = colors[Math.floor(Math.random()*colors.length)];
  console.log(color);
  $('.main').css('background-color',color);
}

$(document).ready(function(){
  changeBackgroundColor();
  $('#message').text(messages[Math.ceil(Math.random()*messages.length)]);
    window.setTimeout(function(){
    $('#premessage').fadeIn(2000).removeClass('hidden');
  },1000);
  window.setTimeout(function(){
    $('#message').fadeIn(2000).removeClass('hidden');
  },4000);
  window.setTimeout(function(){
    $('#next_message').fadeIn(2000).removeClass('hidden');
  },7000);
});

$('#next_message').click(function(){
  $('#next_message').fadeOut('fast');
  changeBackgroundColor();
  $.when($('#message').fadeOut(2000)).done(function(){
    $('#message').text(messages[Math.ceil(Math.random()*messages.length)]);
    $('#message').fadeIn(2000);
    window.setTimeout(function(){
      $('#next_message').fadeIn(2000);
    },7000);
  });
});